config/routes.rb
Rails.application.routes.draw do

  get 'serial', to: 'arduino#serial'
  post 'run_serial', to: 'arduino#run_serial'

  get 'firmata', to: 'arduino#firmata'
  post 'connect_firmata', to: 'arduino#connect_firmata'
  post 'run_firmata', to: 'arduino#run_firmata'

  root 'arduino#serial'

end

app/models/direction.rb
module Direction
  LEFT = 'left'
  RIGHT = 'right'
  UP = 'up'
  DOWN = 'down'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/arduino_controller.rb
class ArduinoController < ApplicationController

  def serial
  end

  def run_serial
    SerialService.move(params[:command])
    render json: {}
  end

  def firmata
  end

  def connect_firmata
    FirmataService.instance.connect
    redirect_to :back
  end

  def run_firmata
    FirmataService.instance.run(params[:command])
    redirect_to :back
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def arrow(direction)
    button_to(run_serial_path(command: direction), remote: true, class: 'btn btn-success btn-lg') do
      tag(:span, class: "glyphicon glyphicon-arrow-#{direction}")
    end
  end

  def laser_toggle
    button_to(run_serial_path(command: 'x'), remote: true, class: 'btn btn-success btn-lg') do
      tag(:span, class: "glyphicon glyphicon-certificate")
    end
  end

end

app/views/arduino/firmata.html.erb
<div class="container">


  <div class="row">
    <div class="col-md-2"><%= button_to(FirmataService.instance.connected? ? 'Connected' : 'Connect', connect_firmata_path, class: "btn btn-#{FirmataService.instance.connected? ? 'success' : 'primary'}") %></div>
  </div>
  <br/>
  <% if FirmataService.instance.connected? %>
      <div class="row">
        <div class="col-md-1"><%= button_to 'Circle', run_firmata_path(command: 'circle'), class: 'btn btn-info' %></div>
        <div class="col-md-1"><%= button_to 'Rose', run_firmata_path(command: 'rose'), class: 'btn btn-info' %></div>
        <div class="col-md-1"><%= button_to 'Spiral', run_firmata_path(command: 'spiral'), class: 'btn btn-info' %></div>
        <div class="col-md-2"><%= button_to 'Stop', run_firmata_path(command: 'stop'), class: 'btn btn-danger' %></div>
      </div>
  <% end %>
</div>

app/views/arduino/serial.html.erb
<div class="container">
  <table class="center-table">
    <tr>
      <td></td>
      <td>
        <%= arrow(Direction::UP) %>
      </td>
      <td></td>
    </tr>
    <tr>
      <td>
        <%= arrow(Direction::LEFT) %>
      </td>
      <td><%= laser_toggle %></td>
      <td>
        <%= arrow(Direction::RIGHT) %>
      </td>
    </tr>
    <tr>
      <td></td>
      <td>
        <%= arrow(Direction::DOWN) %>
      </td>
      <td></td>
    </tr>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Arduino</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Arduino & Ruby</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class=<%= params[:action] == 'serial' ? 'active' : '' %>><%= link_to 'Serial', serial_path %></li>
        <li class=<%= params[:action] == 'firmata' ? 'active' : '' %>><%= link_to 'Firmata', firmata_path %></li>
      </ul>
    </div>
  </div>
</nav>

<%= yield %>

</body>
</html>